// Auto-generated by relay-compiler. Do not edit.

import Relay

struct GameSearchResultRowPreviewQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "GameSearchResultRowPreviewQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameSearchResultRow_game"
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "GameSearchResultRowPreviewQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "name"
                            )),
                            .field(NormalizationLinkedField(
                                name: "asset",
                                alias: "cover",
                                args: [
                                    LiteralArgument(name: "kind", value: "COVER_MEDIUM")
                                ],
                                storageKey: "asset(kind:\"COVER_MEDIUM\")",
                                concreteType: "GameAsset",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "uri"
                                    ))
                                ]
                            )),
                            .field(NormalizationScalarField(
                                name: "id"
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "GameSearchResultRowPreviewQuery",
                operationKind: .query,
                text: """
query GameSearchResultRowPreviewQuery(
  $id: ID!
) {
  game(id: $id) {
    ...GameSearchResultRow_game
    id
  }
}

fragment GameSearchResultRow_game on Game {
  name
  cover: asset(kind: COVER_MEDIUM) {
    uri
  }
}
"""))
    }
}


extension GameSearchResultRowPreviewQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }
}

extension GameSearchResultRowPreviewQuery {
    struct Data: Readable {
        var game: Game_game?

        init(from data: SelectorData) {
            game = data.get(Game_game?.self, "game")
        }

        struct Game_game: Readable, GameSearchResultRow_game_Key {
            var fragment_GameSearchResultRow_game: FragmentPointer

            init(from data: SelectorData) {
                fragment_GameSearchResultRow_game = data.get(fragment: "GameSearchResultRow_game")
            }
        }
    }
}

extension GameSearchResultRowPreviewQuery: Relay.Operation {}
