// Auto-generated by relay-compiler. Do not edit.

import Relay

struct GameSearchResultsPaginationQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "GameSearchResultsPaginationQuery",
                selections: [
                    .field(ReaderLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameSearchResults_games",
                                args: [
                                    VariableArgument(name: "count", variableName: "count"),
                                    VariableArgument(name: "cursor", variableName: "cursor"),
                                    VariableArgument(name: "query", variableName: "query")
                                ]
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "GameSearchResultsPaginationQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "games",
                                args: [
                                    VariableArgument(name: "after", variableName: "cursor"),
                                    ObjectValueArgument(name: "filter", fields: [
                                        VariableArgument(name: "name", variableName: "query")
                                    ]),
                                    VariableArgument(name: "first", variableName: "count")
                                ],
                                concreteType: "GameConnection",
                                plural: false,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "edges",
                                        concreteType: "GameEdge",
                                        plural: true,
                                        selections: [
                                            .field(NormalizationLinkedField(
                                                name: "node",
                                                concreteType: "Game",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "id"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "name"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "__typename"
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "cursor"
                                            ))
                                        ]
                                    )),
                                    .field(NormalizationLinkedField(
                                        name: "pageInfo",
                                        concreteType: "PageInfo",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "endCursor"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "hasNextPage"
                                            ))
                                        ]
                                    ))
                                ]
                            )),
                            .handle(NormalizationHandle(
                                kind: .linked,
                                name: "games",
                                args: [
                                    VariableArgument(name: "after", variableName: "cursor"),
                                    ObjectValueArgument(name: "filter", fields: [
                                        VariableArgument(name: "name", variableName: "query")
                                    ]),
                                    VariableArgument(name: "first", variableName: "count")
                                ],
                                handle: "connection",
                                key: "GameSearchResults_games",
                                filters: ["filter"]
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "GameSearchResultsPaginationQuery",
                operationKind: .query,
                text: """
query GameSearchResultsPaginationQuery(
  $query: String!
  $count: Int = 10
  $cursor: Cursor
) {
  viewer {
    ...GameSearchResults_games_1jWD3d
  }
}

fragment GameSearchResults_games_1jWD3d on Viewer {
  games(filter: {name: $query}, first: $count, after: $cursor) {
    edges {
      node {
        id
        name
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""))
    }
}


extension GameSearchResultsPaginationQuery {
    struct Variables: VariableDataConvertible {
        var query: String
        var count: Int?
        var cursor: String?

        var variableData: VariableData {
            [
                "query": query,
                "count": count,
                "cursor": cursor,
            ]
        }
    }
}

extension GameSearchResultsPaginationQuery {
    struct Data: Readable {
        var viewer: Viewer_viewer?

        init(from data: SelectorData) {
            viewer = data.get(Viewer_viewer?.self, "viewer")
        }

        struct Viewer_viewer: Readable, GameSearchResults_games_Key {
            var fragment_GameSearchResults_games: FragmentPointer

            init(from data: SelectorData) {
                fragment_GameSearchResults_games = data.get(fragment: "GameSearchResults_games")
            }
        }
    }
}

extension GameSearchResultsPaginationQuery: Relay.Operation {}
