// Auto-generated by relay-compiler. Do not edit.

import Relay

struct GameDetailLeaderboardListPreviewQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "GameDetailLeaderboardListPreviewQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameDetailLeaderboardList_game"
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "GameDetailLeaderboardListPreviewQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationLinkedField(
                                name: "categories",
                                concreteType: "Category",
                                plural: true,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "name"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "GameDetailLeaderboardListPreviewQuery",
                operationKind: .query,
                text: """
query GameDetailLeaderboardListPreviewQuery(
  $id: ID!
) {
  game(id: $id) {
    ...GameDetailLeaderboardList_game
    id
  }
}

fragment GameDetailLeaderboardList_game on Game {
  id
  categories {
    id
    name
  }
}
"""))
    }
}


extension GameDetailLeaderboardListPreviewQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }
}

extension GameDetailLeaderboardListPreviewQuery {
    struct Data: Decodable {
        var game: Game_game?

        struct Game_game: Decodable, GameDetailLeaderboardList_game_Key {
            var fragment_GameDetailLeaderboardList_game: FragmentPointer
        }
    }
}

extension GameDetailLeaderboardListPreviewQuery: Relay.Operation {}
