// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct GameDetailLeaderboardList_game {
    public var fragmentPointer: FragmentPointer

    public init(key: GameDetailLeaderboardList_game_Key) {
        fragmentPointer = key.fragment_GameDetailLeaderboardList_game
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "GameDetailLeaderboardList_game",
            type: "Game",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderLinkedField(
                    name: "categories",
                    concreteType: "Category",
                    plural: true,
                    selections: [
                        .field(ReaderScalarField(
                            name: "id"
                        )),
                        .field(ReaderScalarField(
                            name: "name"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension GameDetailLeaderboardList_game {
    public struct Data: Decodable, Identifiable {
        public var id: String
        public var categories: [Category_categories]

        public struct Category_categories: Decodable, Identifiable {
            public var id: String
            public var name: String
        }
    }
}

public protocol GameDetailLeaderboardList_game_Key {
    var fragment_GameDetailLeaderboardList_game: FragmentPointer { get }
}
extension GameDetailLeaderboardList_game: Relay.Fragment {}
extension GameDetailLeaderboardList_game: Relay.RefetchFragment {
    public typealias Operation = GameDetailLeaderboardListRefetchQuery
    public static var metadata: Metadata {
        RefetchMetadata(
            path: ["node"],
            identifierField: "id",
            operation: Operation.self
        )
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI
extension GameDetailLeaderboardList_game_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<GameDetailLeaderboardList_game> {
        RelaySwiftUI.FragmentNext<GameDetailLeaderboardList_game>(self)
    }
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.RefetchableFragment<GameDetailLeaderboardList_game> {
        RelaySwiftUI.RefetchableFragment<GameDetailLeaderboardList_game>(self)
    }
}
#endif