// Auto-generated by relay-compiler. Do not edit.

import Relay

struct GameDetailScreenQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "GameDetailScreenQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameDetailHeader_game"
                            )),
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameDetailLeaderboardList_game"
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "GameDetailScreenQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationScalarField(
                                name: "name"
                            )),
                            .field(NormalizationLinkedField(
                                name: "asset",
                                alias: "cover",
                                args: [
                                    LiteralArgument(name: "kind", value: "COVER_MEDIUM")
                                ],
                                storageKey: "asset(kind:\"COVER_MEDIUM\")",
                                concreteType: "GameAsset",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "uri"
                                    ))
                                ]
                            )),
                            .field(NormalizationLinkedField(
                                name: "categories",
                                concreteType: "Category",
                                plural: true,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "name"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "GameDetailScreenQuery",
                operationKind: .query,
                text: """
query GameDetailScreenQuery(
  $id: ID!
) {
  game(id: $id) {
    id
    ...GameDetailHeader_game
    ...GameDetailLeaderboardList_game
  }
}

fragment GameDetailHeader_game on Game {
  name
  cover: asset(kind: COVER_MEDIUM) {
    uri
  }
}

fragment GameDetailLeaderboardList_game on Game {
  id
  categories {
    id
    name
  }
}
"""))
    }
}


extension GameDetailScreenQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }

    init(id: String) {
        self.init(variables: .init(id: id))
    }
}

extension GameDetailScreenQuery {
    struct Data: Decodable {
        var game: Game_game?

        struct Game_game: Decodable, Identifiable, GameDetailHeader_game_Key, GameDetailLeaderboardList_game_Key {
            var id: String
            var fragment_GameDetailHeader_game: FragmentPointer
            var fragment_GameDetailLeaderboardList_game: FragmentPointer
        }
    }
}

extension GameDetailScreenQuery: Relay.Operation {}
