// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct GameDetailScreenQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "GameDetailScreenQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameDetailHeader_game"
                            )),
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "GameDetailLeaderboardList_game"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "GameDetailScreenQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "game",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "Game",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationScalarField(
                                name: "name"
                            )),
                            .field(NormalizationLinkedField(
                                name: "asset",
                                alias: "cover",
                                args: [
                                    LiteralArgument(name: "kind", value: "COVER_MEDIUM")
                                ],
                                storageKey: "asset(kind:\"COVER_MEDIUM\")",
                                concreteType: "GameAsset",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "uri"
                                    ))
                                ]
                            )),
                            .field(NormalizationLinkedField(
                                name: "categories",
                                concreteType: "Category",
                                plural: true,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "name"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "GameDetailScreenQuery",
                operationKind: .query,
                text: """
query GameDetailScreenQuery(
  $id: ID!
) {
  game(id: $id) {
    id
    ...GameDetailHeader_game
    ...GameDetailLeaderboardList_game
  }
}

fragment GameDetailHeader_game on Game {
  name
  cover: asset(kind: COVER_MEDIUM) {
    uri
  }
}

fragment GameDetailLeaderboardList_game on Game {
  id
  categories {
    id
    name
  }
}
"""
            )
        )
    }
}

extension GameDetailScreenQuery {
    public struct Variables: VariableDataConvertible {
        public var id: String

        public init(id: String) {
            self.id = id
        }

        public var variableData: VariableData {
            [
                "id": id
            ]
        }
    }

    public init(id: String) {
        self.init(variables: .init(id: id))
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)extension RelaySwiftUI.QueryNext.WrappedValue where O == GameDetailScreenQuery {
    public func get(id: String, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<GameDetailScreenQuery>.Result {
        self.get(.init(id: id), fetchKey: fetchKey)
    }
}
#endif
extension GameDetailScreenQuery {
    public struct Data: Decodable {
        public var game: Game_game?

        public struct Game_game: Decodable, Identifiable, GameDetailHeader_game_Key, GameDetailLeaderboardList_game_Key {
            public var id: String
            public var fragment_GameDetailHeader_game: FragmentPointer
            public var fragment_GameDetailLeaderboardList_game: FragmentPointer
        }
    }
}
extension GameDetailScreenQuery: Relay.Operation {}