// Auto-generated by relay-compiler. Do not edit.

import Relay

struct GameDetailLeaderboardList_game {
    var fragmentPointer: FragmentPointer

    init(key: GameDetailLeaderboardList_game_Key) {
        fragmentPointer = key.fragment_GameDetailLeaderboardList_game
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "GameDetailLeaderboardList_game",
            type: "Game",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderLinkedField(
                    name: "categories",
                    concreteType: "Category",
                    plural: true,
                    selections: [
                        .field(ReaderScalarField(
                            name: "id"
                        )),
                        .field(ReaderScalarField(
                            name: "name"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension GameDetailLeaderboardList_game {
    struct Data: Decodable, Identifiable {
        var id: String
        var categories: [Category_categories]

        struct Category_categories: Decodable, Identifiable {
            var id: String
            var name: String
        }
    }
}

protocol GameDetailLeaderboardList_game_Key {
    var fragment_GameDetailLeaderboardList_game: FragmentPointer { get }
}

extension GameDetailLeaderboardList_game: Relay.Fragment {}

extension GameDetailLeaderboardList_game: Relay.RefetchFragment {
    typealias Operation = GameDetailLeaderboardListRefetchQuery
    static var metadata: Metadata {
        RefetchMetadata(
            path: ["node"],
            identifierField: "id",
            operation: Operation.self
        )
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension GameDetailLeaderboardList_game_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<GameDetailLeaderboardList_game> {
        RelaySwiftUI.FragmentNext<GameDetailLeaderboardList_game>(self)
    }
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.RefetchableFragment<GameDetailLeaderboardList_game> {
        RelaySwiftUI.RefetchableFragment<GameDetailLeaderboardList_game>(self)
    }
}
#endif