// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct LeaderboardRun_run {
    public var fragmentPointer: FragmentPointer

    public init(key: LeaderboardRun_run_Key) {
        fragmentPointer = key.fragment_LeaderboardRun_run
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "LeaderboardRun_run",
            type: "PlacedRun",
            selections: [
                .field(ReaderScalarField(
                    name: "place"
                )),
                .field(ReaderLinkedField(
                    name: "run",
                    concreteType: "Run",
                    plural: false,
                    selections: [
                        .field(ReaderScalarField(
                            name: "id"
                        )),
                        .field(ReaderScalarField(
                            name: "comment"
                        )),
                        .field(ReaderScalarField(
                            name: "time"
                        )),
                        .field(ReaderLinkedField(
                            name: "players",
                            plural: true,
                            selections: [
                                .inlineFragment(ReaderInlineFragment(
                                    type: "UserRunPlayer",
                                    selections: [
                                        .field(ReaderLinkedField(
                                            name: "user",
                                            concreteType: "User",
                                            plural: false,
                                            selections: [
                                                .field(ReaderScalarField(
                                                    name: "name"
                                                ))
                                            ]
                                        ))
                                    ]
                                )),
                                .inlineFragment(ReaderInlineFragment(
                                    type: "GuestRunPlayer",
                                    selections: [
                                        .field(ReaderScalarField(
                                            name: "name"
                                        ))
                                    ]
                                ))
                            ]
                        ))
                    ]
                ))
            ]
        )
    }
}

extension LeaderboardRun_run {
    public struct Data: Decodable {
        public var place: Int
        public var run: Run_run

        public struct Run_run: Decodable, Identifiable {
            public var id: String
            public var comment: String
            public var time: Double?
            public var players: [RunPlayer_players]

            public enum RunPlayer_players: Decodable {
                case userRunPlayer(UserRunPlayer)
                case guestRunPlayer(GuestRunPlayer)
                case runPlayer(RunPlayer)

                private enum TypeKeys: String, CodingKey {
                    case __typename
                }

                public init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: TypeKeys.self)
                    let typeName = try container.decode(String.self, forKey: .__typename)
                    switch typeName {
                    case "UserRunPlayer":
                        self = .userRunPlayer(try UserRunPlayer(from: decoder))
                    case "GuestRunPlayer":
                        self = .guestRunPlayer(try GuestRunPlayer(from: decoder))
                    default:
                        self = .runPlayer(try RunPlayer(from: decoder))
                    }
                }

                public var asUserRunPlayer: UserRunPlayer? {
                    if case .userRunPlayer(let val) = self {
                        return val
                    }
                    return nil
                }

                public var asGuestRunPlayer: GuestRunPlayer? {
                    if case .guestRunPlayer(let val) = self {
                        return val
                    }
                    return nil
                }

                public var asRunPlayer: RunPlayer? {
                    if case .runPlayer(let val) = self {
                        return val
                    }
                    return nil
                }

                public struct UserRunPlayer: Decodable {
                    public var user: User_user?

                    public struct User_user: Decodable {
                        public var name: String?
                    }
                }

                public struct GuestRunPlayer: Decodable {
                    public var name: String
                }

                public struct RunPlayer: Decodable {
                }
            }
        }
    }
}

public protocol LeaderboardRun_run_Key {
    var fragment_LeaderboardRun_run: FragmentPointer { get }
}
extension LeaderboardRun_run: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI
extension LeaderboardRun_run_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<LeaderboardRun_run> {
        RelaySwiftUI.FragmentNext<LeaderboardRun_run>(self)
    }
}
#endif