// Auto-generated by relay-compiler. Do not edit.

import Relay

struct LeaderboardRunsList_leaderboard {
    var fragmentPointer: FragmentPointer

    init(key: LeaderboardRunsList_leaderboard_Key) {
        fragmentPointer = key.fragment_LeaderboardRunsList_leaderboard
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "LeaderboardRunsList_leaderboard",
            type: "Leaderboard",
            selections: [
                .field(ReaderLinkedField(
                    name: "runs",
                    args: [
                        VariableArgument(name: "first", variableName: "count")
                    ],
                    concreteType: "PlacedRun",
                    plural: true,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "run",
                            concreteType: "Run",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "id"
                                ))
                            ]
                        )),
                        .fragmentSpread(ReaderFragmentSpread(
                            name: "LeaderboardRun_run"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension LeaderboardRunsList_leaderboard {
    struct Data: Decodable {
        var runs: [PlacedRun_runs]

        struct PlacedRun_runs: Decodable, LeaderboardRun_run_Key {
            var run: Run_run
            var fragment_LeaderboardRun_run: FragmentPointer

            struct Run_run: Decodable, Identifiable {
                var id: String
            }
        }
    }
}

protocol LeaderboardRunsList_leaderboard_Key {
    var fragment_LeaderboardRunsList_leaderboard: FragmentPointer { get }
}

extension LeaderboardRunsList_leaderboard: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension LeaderboardRunsList_leaderboard_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<LeaderboardRunsList_leaderboard> {
        RelaySwiftUI.FragmentNext<LeaderboardRunsList_leaderboard>(self)
    }
}
#endif