// Auto-generated by relay-compiler. Do not edit.

import Relay

struct LeaderboardRunsList_leaderboard {
    var fragmentPointer: FragmentPointer

    init(key: LeaderboardRunsList_leaderboard_Key) {
        fragmentPointer = key.fragment_LeaderboardRunsList_leaderboard
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "LeaderboardRunsList_leaderboard",
            type: "Leaderboard",
            selections: [
                .field(ReaderLinkedField(
                    name: "runs",
                    args: [
                        VariableArgument(name: "first", variableName: "count")
                    ],
                    concreteType: "PlacedRun",
                    plural: true,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "run",
                            concreteType: "Run",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "id"
                                ))
                            ]
                        )),
                        .fragmentSpread(ReaderFragmentSpread(
                            name: "LeaderboardRun_run"
                        ))
                    ]
                ))
            ])
    }
}


extension LeaderboardRunsList_leaderboard {
    struct Data: Readable {
        var runs: [PlacedRun_runs]

        init(from data: SelectorData) {
            runs = data.get([PlacedRun_runs].self, "runs")
        }

        struct PlacedRun_runs: Readable, LeaderboardRun_run_Key {
            var run: Run_run
            var fragment_LeaderboardRun_run: FragmentPointer

            init(from data: SelectorData) {
                run = data.get(Run_run.self, "run")
                fragment_LeaderboardRun_run = data.get(fragment: "LeaderboardRun_run")
            }

            struct Run_run: Readable {
                var id: String

                init(from data: SelectorData) {
                    id = data.get(String.self, "id")
                }
            }
        }
    }
}

protocol LeaderboardRunsList_leaderboard_Key {
    var fragment_LeaderboardRunsList_leaderboard: FragmentPointer { get }
}

extension LeaderboardRunsList_leaderboard: Relay.Fragment {}
