// Auto-generated by relay-compiler. Do not edit.

import Relay

struct RunPlayerRow_player {
    var fragmentPointer: FragmentPointer

    init(key: RunPlayerRow_player_Key) {
        fragmentPointer = key.fragment_RunPlayerRow_player
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "RunPlayerRow_player",
            type: "RunPlayer",
            selections: [
                .inlineFragment(ReaderInlineFragment(
                    type: "UserRunPlayer",
                    selections: [
                        .field(ReaderLinkedField(
                            name: "user",
                            concreteType: "User",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "name"
                                )),
                                .field(ReaderLinkedField(
                                    name: "nameStyle",
                                    plural: false,
                                    selections: [
                                        .inlineFragment(ReaderInlineFragment(
                                            type: "SolidUserNameStyle",
                                            selections: [
                                                .field(ReaderLinkedField(
                                                    name: "color",
                                                    concreteType: "Color",
                                                    plural: false,
                                                    selections: [
                                                        .field(ReaderScalarField(
                                                            name: "light"
                                                        ))
                                                    ]
                                                ))
                                            ]
                                        )),
                                        .inlineFragment(ReaderInlineFragment(
                                            type: "GradientUserNameStyle",
                                            selections: [
                                                .field(ReaderLinkedField(
                                                    name: "fromColor",
                                                    concreteType: "Color",
                                                    plural: false,
                                                    selections: [
                                                        .field(ReaderScalarField(
                                                            name: "light"
                                                        ))
                                                    ]
                                                )),
                                                .field(ReaderLinkedField(
                                                    name: "toColor",
                                                    concreteType: "Color",
                                                    plural: false,
                                                    selections: [
                                                        .field(ReaderScalarField(
                                                            name: "light"
                                                        ))
                                                    ]
                                                ))
                                            ]
                                        ))
                                    ]
                                ))
                            ]
                        ))
                    ]
                )),
                .inlineFragment(ReaderInlineFragment(
                    type: "GuestRunPlayer",
                    selections: [
                        .field(ReaderScalarField(
                            name: "name"
                        ))
                    ]
                ))
            ])
    }
}


extension RunPlayerRow_player {
    enum Data: Readable {
        case userRunPlayer(UserRunPlayer)
        case guestRunPlayer(GuestRunPlayer)
        case unknown
  
        init(from data: SelectorData) {
            let typeName = data.get(String.self, "__typename")
            switch typeName {
            case "UserRunPlayer":
                self = .userRunPlayer(UserRunPlayer(from: data))
            case "GuestRunPlayer":
                self = .guestRunPlayer(GuestRunPlayer(from: data))
            default:
                self = .unknown
            }
        }

        var asUserRunPlayer: UserRunPlayer? {
            if case .userRunPlayer(let val) = self {
                return val
            }
            return nil
        }

        var asGuestRunPlayer: GuestRunPlayer? {
            if case .guestRunPlayer(let val) = self {
                return val
            }
            return nil
        }

        struct UserRunPlayer: Readable {
            var user: User_user?

            init(from data: SelectorData) {
                user = data.get(User_user?.self, "user")
            }

            struct User_user: Readable {
                var name: String?
                var nameStyle: UserNameStyle_nameStyle

                init(from data: SelectorData) {
                    name = data.get(String?.self, "name")
                    nameStyle = data.get(UserNameStyle_nameStyle.self, "nameStyle")
                }

                enum UserNameStyle_nameStyle: Readable {
                    case solidUserNameStyle(SolidUserNameStyle)
                    case gradientUserNameStyle(GradientUserNameStyle)
                    case unknown
  
                    init(from data: SelectorData) {
                        let typeName = data.get(String.self, "__typename")
                        switch typeName {
                        case "SolidUserNameStyle":
                            self = .solidUserNameStyle(SolidUserNameStyle(from: data))
                        case "GradientUserNameStyle":
                            self = .gradientUserNameStyle(GradientUserNameStyle(from: data))
                        default:
                            self = .unknown
                        }
                    }

                    var asSolidUserNameStyle: SolidUserNameStyle? {
                        if case .solidUserNameStyle(let val) = self {
                            return val
                        }
                        return nil
                    }

                    var asGradientUserNameStyle: GradientUserNameStyle? {
                        if case .gradientUserNameStyle(let val) = self {
                            return val
                        }
                        return nil
                    }

                    struct SolidUserNameStyle: Readable {
                        var color: Color_color

                        init(from data: SelectorData) {
                            color = data.get(Color_color.self, "color")
                        }

                        struct Color_color: Readable {
                            var light: String

                            init(from data: SelectorData) {
                                light = data.get(String.self, "light")
                            }
                        }
                    }

                    struct GradientUserNameStyle: Readable {
                        var fromColor: Color_fromColor
                        var toColor: Color_toColor

                        init(from data: SelectorData) {
                            fromColor = data.get(Color_fromColor.self, "fromColor")
                            toColor = data.get(Color_toColor.self, "toColor")
                        }

                        struct Color_fromColor: Readable {
                            var light: String

                            init(from data: SelectorData) {
                                light = data.get(String.self, "light")
                            }
                        }

                        struct Color_toColor: Readable {
                            var light: String

                            init(from data: SelectorData) {
                                light = data.get(String.self, "light")
                            }
                        }
                    }
                }
            }
        }

        struct GuestRunPlayer: Readable {
            var name: String

            init(from data: SelectorData) {
                name = data.get(String.self, "name")
            }
        }
    }
}

protocol RunPlayerRow_player_Key {
    var fragment_RunPlayerRow_player: FragmentPointer { get }
}

extension RunPlayerRow_player: Relay.Fragment {}
