// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct LeaderboardScreenQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "LeaderboardScreenQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(ReaderLinkedField(
                                name: "leaderboard",
                                args: [
                                    VariableArgument(name: "category", variableName: "categoryID"),
                                    VariableArgument(name: "game", variableName: "gameID"),
                                    VariableArgument(name: "level", variableName: "levelID")
                                ],
                                concreteType: "Leaderboard",
                                plural: false,
                                selections: [
                                    .field(ReaderLinkedField(
                                        name: "game",
                                        concreteType: "Game",
                                        plural: false,
                                        selections: [
                                            .fragmentSpread(ReaderFragmentSpread(
                                                name: "LeaderboardHeader_game"
                                            ))
                                        ]
                                    )),
                                    .field(ReaderLinkedField(
                                        name: "category",
                                        concreteType: "Category",
                                        plural: false,
                                        selections: [
                                            .fragmentSpread(ReaderFragmentSpread(
                                                name: "LeaderboardHeader_category"
                                            ))
                                        ]
                                    )),
                                    .fragmentSpread(ReaderFragmentSpread(
                                        name: "LeaderboardRunsList_leaderboard",
                                        args: [
                                            LiteralArgument(name: "count", value: 50)
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "LeaderboardScreenQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "leaderboard",
                                args: [
                                    VariableArgument(name: "category", variableName: "categoryID"),
                                    VariableArgument(name: "game", variableName: "gameID"),
                                    VariableArgument(name: "level", variableName: "levelID")
                                ],
                                concreteType: "Leaderboard",
                                plural: false,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "game",
                                        concreteType: "Game",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "name"
                                            )),
                                            .field(NormalizationLinkedField(
                                                name: "asset",
                                                alias: "cover",
                                                args: [
                                                    LiteralArgument(name: "kind", value: "COVER_MEDIUM")
                                                ],
                                                storageKey: "asset(kind:\"COVER_MEDIUM\")",
                                                concreteType: "GameAsset",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "uri"
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "id"
                                            ))
                                        ]
                                    )),
                                    .field(NormalizationLinkedField(
                                        name: "category",
                                        concreteType: "Category",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "name"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "id"
                                            ))
                                        ]
                                    )),
                                    .field(NormalizationLinkedField(
                                        name: "runs",
                                        args: [
                                            LiteralArgument(name: "first", value: 50)
                                        ],
                                        storageKey: "runs(first:50)",
                                        concreteType: "PlacedRun",
                                        plural: true,
                                        selections: [
                                            .field(NormalizationLinkedField(
                                                name: "run",
                                                concreteType: "Run",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "id"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "comment"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "time"
                                                    )),
                                                    .field(NormalizationLinkedField(
                                                        name: "players",
                                                        plural: true,
                                                        selections: [
                                                            .field(NormalizationScalarField(
                                                                name: "__typename"
                                                            )),
                                                            .inlineFragment(NormalizationInlineFragment(
                                                                type: "UserRunPlayer",
                                                                selections: [
                                                                    .field(NormalizationLinkedField(
                                                                        name: "user",
                                                                        concreteType: "User",
                                                                        plural: false,
                                                                        selections: [
                                                                            .field(NormalizationScalarField(
                                                                                name: "name"
                                                                            )),
                                                                            .field(NormalizationScalarField(
                                                                                name: "id"
                                                                            ))
                                                                        ]
                                                                    ))
                                                                ]
                                                            )),
                                                            .inlineFragment(NormalizationInlineFragment(
                                                                type: "GuestRunPlayer",
                                                                selections: [
                                                                    .field(NormalizationScalarField(
                                                                        name: "name"
                                                                    ))
                                                                ]
                                                            ))
                                                        ]
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "place"
                                            ))
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "LeaderboardScreenQuery",
                operationKind: .query,
                text: """
query LeaderboardScreenQuery(
  $gameID: ID!
  $categoryID: ID!
  $levelID: ID
) {
  viewer {
    leaderboard(game: $gameID, category: $categoryID, level: $levelID) {
      game {
        ...LeaderboardHeader_game
        id
      }
      category {
        ...LeaderboardHeader_category
        id
      }
      ...LeaderboardRunsList_leaderboard_knr29
    }
  }
}

fragment LeaderboardHeader_category on Category {
  name
}

fragment LeaderboardHeader_game on Game {
  name
  cover: asset(kind: COVER_MEDIUM) {
    uri
  }
}

fragment LeaderboardRun_run on PlacedRun {
  place
  run {
    id
    comment
    time
    players {
      __typename
      ... on UserRunPlayer {
        user {
          name
          id
        }
      }
      ... on GuestRunPlayer {
        name
      }
    }
  }
}

fragment LeaderboardRunsList_leaderboard_knr29 on Leaderboard {
  runs(first: 50) {
    run {
      id
    }
    place
    ...LeaderboardRun_run
  }
}
"""
            )
        )
    }
}

extension LeaderboardScreenQuery {
    public struct Variables: VariableDataConvertible {
        public var gameID: String
        public var categoryID: String
        public var levelID: String?

        public init(gameID: String, categoryID: String, levelID: String? = nil) {
            self.gameID = gameID
            self.categoryID = categoryID
            self.levelID = levelID
        }

        public var variableData: VariableData {
            [
                "gameID": gameID,
                "categoryID": categoryID,
                "levelID": levelID
            ]
        }
    }

    public init(gameID: String, categoryID: String, levelID: String? = nil) {
        self.init(variables: .init(gameID: gameID, categoryID: categoryID, levelID: levelID))
    }
}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.Query.WrappedValue where O == LeaderboardScreenQuery {
    public func get(gameID: String, categoryID: String, levelID: String? = nil, fetchKey: Any? = nil) -> RelaySwiftUI.Query<LeaderboardScreenQuery>.Result {
        self.get(.init(gameID: gameID, categoryID: categoryID, levelID: levelID), fetchKey: fetchKey)
    }
}
#endif

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == LeaderboardScreenQuery {
    public func refetch(gameID: String, categoryID: String, levelID: String? = nil) {
        self.refetch(.init(gameID: gameID, categoryID: categoryID, levelID: levelID))
    }
}
#endif

extension LeaderboardScreenQuery {
    public struct Data: Decodable {
        public var viewer: Viewer_viewer?

        public struct Viewer_viewer: Decodable {
            public var leaderboard: Leaderboard_leaderboard?

            public struct Leaderboard_leaderboard: Decodable, LeaderboardRunsList_leaderboard_Key {
                public var game: Game_game
                public var category: Category_category
                public var fragment_LeaderboardRunsList_leaderboard: FragmentPointer

                public struct Game_game: Decodable, LeaderboardHeader_game_Key {
                    public var fragment_LeaderboardHeader_game: FragmentPointer
                }

                public struct Category_category: Decodable, LeaderboardHeader_category_Key {
                    public var fragment_LeaderboardHeader_category: FragmentPointer
                }
            }
        }
    }
}

extension LeaderboardScreenQuery: Relay.Operation {}