// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct LeaderboardRunsList_leaderboard {
    public var fragmentPointer: FragmentPointer

    public init(key: LeaderboardRunsList_leaderboard_Key) {
        fragmentPointer = key.fragment_LeaderboardRunsList_leaderboard
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "LeaderboardRunsList_leaderboard",
            type: "Leaderboard",
            selections: [
                .field(ReaderLinkedField(
                    name: "runs",
                    args: [
                        VariableArgument(name: "first", variableName: "count")
                    ],
                    concreteType: "PlacedRun",
                    plural: true,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "run",
                            concreteType: "Run",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "id"
                                ))
                            ]
                        )),
                        .field(ReaderScalarField(
                            name: "place"
                        )),
                        .fragmentSpread(ReaderFragmentSpread(
                            name: "LeaderboardRun_run"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension LeaderboardRunsList_leaderboard {
    public struct Data: Decodable {
        public var runs: [PlacedRun_runs]

        public struct PlacedRun_runs: Decodable, LeaderboardRun_run_Key {
            public var run: Run_run
            public var place: Int
            public var fragment_LeaderboardRun_run: FragmentPointer

            public struct Run_run: Decodable, Identifiable {
                public var id: String
            }
        }
    }
}

public protocol LeaderboardRunsList_leaderboard_Key {
    var fragment_LeaderboardRunsList_leaderboard: FragmentPointer { get }
}

extension LeaderboardRunsList_leaderboard: Relay.Fragment {}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension LeaderboardRunsList_leaderboard_Key {
    public func asFragment() -> RelaySwiftUI.Fragment<LeaderboardRunsList_leaderboard> {
        RelaySwiftUI.Fragment<LeaderboardRunsList_leaderboard>(self)
    }
}
#endif