// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct LeaderboardRunPreviewQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "LeaderboardRunPreviewQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(ReaderLinkedField(
                                name: "leaderboard",
                                storageKey: "leaderboard(category:\"bar\",game:\"foo\")",
                                args: [
                                    LiteralArgument(name: "category", value: "bar"),
                                    LiteralArgument(name: "game", value: "foo")
                                ],
                                concreteType: "Leaderboard",
                                plural: false,
                                selections: [
                                    .field(ReaderLinkedField(
                                        name: "runs",
                                        concreteType: "PlacedRun",
                                        plural: true,
                                        selections: [
                                            .field(ReaderLinkedField(
                                                name: "run",
                                                concreteType: "Run",
                                                plural: false,
                                                selections: [
                                                    .field(ReaderScalarField(
                                                        name: "id"
                                                    ))
                                                ]
                                            )),
                                            .fragmentSpread(ReaderFragmentSpread(
                                                name: "LeaderboardRun_run"
                                            ))
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "LeaderboardRunPreviewQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "leaderboard",
                                args: [
                                    LiteralArgument(name: "category", value: "bar"),
                                    LiteralArgument(name: "game", value: "foo")
                                ],
                                storageKey: "leaderboard(category:\"bar\",game:\"foo\")",
                                concreteType: "Leaderboard",
                                plural: false,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "runs",
                                        concreteType: "PlacedRun",
                                        plural: true,
                                        selections: [
                                            .field(NormalizationLinkedField(
                                                name: "run",
                                                concreteType: "Run",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "id"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "comment"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "time"
                                                    )),
                                                    .field(NormalizationLinkedField(
                                                        name: "players",
                                                        plural: true,
                                                        selections: [
                                                            .field(NormalizationScalarField(
                                                                name: "__typename"
                                                            )),
                                                            .inlineFragment(NormalizationInlineFragment(
                                                                type: "UserRunPlayer",
                                                                selections: [
                                                                    .field(NormalizationLinkedField(
                                                                        name: "user",
                                                                        concreteType: "User",
                                                                        plural: false,
                                                                        selections: [
                                                                            .field(NormalizationScalarField(
                                                                                name: "name"
                                                                            )),
                                                                            .field(NormalizationScalarField(
                                                                                name: "id"
                                                                            ))
                                                                        ]
                                                                    ))
                                                                ]
                                                            )),
                                                            .inlineFragment(NormalizationInlineFragment(
                                                                type: "GuestRunPlayer",
                                                                selections: [
                                                                    .field(NormalizationScalarField(
                                                                        name: "name"
                                                                    ))
                                                                ]
                                                            ))
                                                        ]
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "place"
                                            ))
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "LeaderboardRunPreviewQuery",
                operationKind: .query,
                text: """
query LeaderboardRunPreviewQuery {
  viewer {
    leaderboard(game: "foo", category: "bar") {
      runs {
        run {
          id
        }
        ...LeaderboardRun_run
      }
    }
  }
}

fragment LeaderboardRun_run on PlacedRun {
  place
  run {
    id
    comment
    time
    players {
      __typename
      ... on UserRunPlayer {
        user {
          name
          id
        }
      }
      ... on GuestRunPlayer {
        name
      }
    }
  }
}
"""
            )
        )
    }
}

extension LeaderboardRunPreviewQuery {
    public typealias Variables = EmptyVariables
}



extension LeaderboardRunPreviewQuery {
    public struct Data: Decodable {
        public var viewer: Viewer_viewer?

        public struct Viewer_viewer: Decodable {
            public var leaderboard: Leaderboard_leaderboard?

            public struct Leaderboard_leaderboard: Decodable {
                public var runs: [PlacedRun_runs]

                public struct PlacedRun_runs: Decodable, LeaderboardRun_run_Key {
                    public var run: Run_run
                    public var fragment_LeaderboardRun_run: FragmentPointer

                    public struct Run_run: Decodable, Identifiable {
                        public var id: String
                    }
                }
            }
        }
    }
}

extension LeaderboardRunPreviewQuery: Relay.Operation {}