name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_app:
    name: Build app
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 12 beta
      run: sudo xcode-select -s /Applications/Xcode_12_beta.app
    - name: Build app
      run: |
        set -eo pipefail
        xcodebuild \
          -scheme Speedrun \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
          test | xcpretty